version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  server:
    build: ./server
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/pakproperty
      - NODE_ENV=development
    depends_on:
      - mongo
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
volumes:
  mongo_data: 