services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - server/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/pakproperty
      - NODE_ENV=development
    depends_on:
      mongo:
        condition: service_healthy
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
volumes:
  mongo_data: 