services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - server/.env
    environment:
      - MONGODB_URI=mongodb://admin:iSuperCoder_Admin_2025_Secure_Key_9f8e7d6c5b4a3928@database:27017/pakproperty?authSource=admin
      - NODE_ENV=production
    networks:
      - production_isupercoder-prod
    external_links:
      - database
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=production
    depends_on:
      - server

networks:
  production_isupercoder-prod:
    external: true