services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123

  mongo-express:
    image: mongo-express:1.0.0
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password123
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    depends_on:
      mongo:
        condition: service_healthy

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - server/.env
    environment:
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/pakproperty?authSource=admin
      - NODE_ENV=development
    depends_on:
      mongo:
        condition: service_healthy
  client:
    build: ./client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - server
volumes:
  mongo_data: 